In [1]:
print("wellcom back master. let's start what you do.")

wellcom back master. let's start what you do.


In [2]:
###import module you need.
import numpy
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer as CV
###contenued...
###For test
from sklearn.decomposition import LatentDirichletAllocation as LDA

print('completed')

completed


In [3]:
###set datasets.
categorise = ['rec.sport.baseball','sci.space','comp.sys.mac.hardware','comp.windows.x']

news20 = fetch_20newsgroups(categories=categorise)
news = news20.data

news

2.2.22.80\n',
 "From: jcav@ellis.uchicago.edu (JohnC)\nSubject: how do you like the Apple Color OneScanner?\nReply-To: jcav@midway.uchicago.edu\nOrganization: The Royal Society for Putting Things on Top of Other Things\nLines: 13\n\nWe're all set to buy one of these for the office, to use for scanning in\ncolor photographs and for optical character recognition.  We've played with\nthe original grayscale OneScanner and were very pleased.  Is the color model\ncomparable in quality?\n\nAlso, what brand of OCR software would you recommend?  We're leaning toward\nCaere OmniPage.  Any better ideas?  Thanks.\n\n-- \nJohn Cavallino                  |  EMail: jcav@midway.uchicago.edu\nUniversity of Chicago Hospitals |         John_Cavallino@uchfm.bsd.uchicago.edu\nOffice of Facilities Management | USMail: 5841 S. Maryland Ave, MC 0953\nB0 f++ w c+ g++ k+ s++ e h- p   |         Chicago, IL  60637\n",
 "Subject: Re: 68LC040 vs. 68RC040 in Centris 650\nFrom: Bruce@hoult.actrix.gen.nz (Bruce Hoult)

In [4]:
###The cell for test Countvectrizer
txt_vec = CV(max_df=0.9, min_df=5, stop_words='english')
txt_vec_fit = txt_vec.fit(news)
txt_vec.get_feature_names()

['00',
 '000',
 '0005',
 '0062',
 '00mbstultz',
 '01',
 '01wb',
 '02',
 '0200',
 '0223',
 '024222',
 '03',
 '030',
 '033',
 '04',
 '040',
 '0400',
 '05',
 '051',
 '06',
 '07',
 '08',
 '09',
 '0ha',
 '10',
 '100',
 '1000',
 '100m',
 '101',
 '102',
 '1024',
 '1024x768',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109',
 '10th',
 '11',
 '110',
 '111',
 '11181',
 '112',
 '113',
 '114',
 '1141',
 '115',
 '117',
 '118',
 '119',
 '11th',
 '12',
 '120',
 '1200',
 '120399',
 '121',
 '122',
 '123',
 '124',
 '125',
 '126',
 '127',
 '128',
 '129',
 '13',
 '130',
 '1304',
 '131',
 '132',
 '133',
 '134',
 '135',
 '136',
 '137',
 '138',
 '139',
 '14',
 '140',
 '1400',
 '141',
 '142',
 '143',
 '1430',
 '144',
 '144750',
 '145',
 '146',
 '14691229',
 '147',
 '148',
 '14853',
 '149',
 '15',
 '150',
 '1500',
 '151',
 '152',
 '153',
 '154',
 '155',
 '156',
 '1568',
 '158',
 '15apr93',
 '15th',
 '16',
 '160',
 '1600',
 '161',
 '162',
 '16330',
 '164',
 '167',
 '168730',
 '16mb',
 '16mhz',
 '17',
 '17

In [5]:
len(txt_vec.get_feature_names())


7905

----------------------------------------------------------------------
こっからいじるよ
----------------------------------------------------------------------

In [14]:
###declear the variable.
K = 3#the number of topic
alpha = 0.5#hyper parameter for default topic
beta = 0.5#hyper parameter for defoult wards
print('completed')

completed


コーパスの読み込みとカウンタ
これはcountvectorierを使う

In [19]:
M = len(txt_vec.get_feature_names())
#Vもおなじ？

z_m_n = []
n_m_z = numpy.zeros((M,K)) + alpha
n_z_t = numpy.zeros((K,M)) + beta
n_z = numpy.zeros(K) + M * beta

N=0


In [22]:
for m, doc enumerate(docs):

SyntaxError: invalid syntax (<ipython-input-22-3cb05316cc1e>, line 1)

-----------------------------------------
よくわかんないけどここまでいじったよ
-----------------------------------------

In [6]:
lda = LDA(n_components=3, learning_method='online')
lda.fit(txt_vec_fit.transform(news))

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='online', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=3, n_jobs=None,
                          perp_tol=0.1, random_state=None,
                          topic_word_prior=None, total_samples=1000000.0,
                          verbose=0)

In [7]:
features = txt_vec.get_feature_names()


#↓ここに書いてることよくわからんチン
for tn in range(3):
    print("topic "+str(tn))#というかここから下がどうなってるかわからん
    row = lda.components_[tn]
    words = ', '.join([features[i] for i in row.argsort()[:-20:-1]])
    print(words, "\n")

topic 0
edu, writes, article, year, com, university, good, don, think, posting, team, nntp, host, baseball, just, game, like, cs, better 

topic 1
space, edu, nasa, com, gov, writes, article, launch, like, just, earth, posting, moon, orbit, access, data, nntp, host, lunar 

topic 2
edu, com, window, use, file, host, posting, mit, nntp, mac, server, like, problem, does, program, apple, know, motif, available 



In [9]:
# predict
text11="an American multinational technology company headquartered in Cupertino, "+ \
        "California, that designs, develops, and sells consumer electronics,"+ \
        "computer software, and online services."

text12="The company's hardware products include the iPhone smartphone,"+ \
        "the iPad tablet computer, the Mac personal computer,"+ \
        "the iPod portable media player, the Apple Watch smartwatch,"+ \
        "the Apple TV digital media player, and the HomePod smart speaker."

text13="there are nany baseball teams in the world,and a lot of team has students "+ \
        "many student and pro sports player is playing by same rule"+ \
        "becouse many people can playing baseball,and baseball is enjoyed by many people."

document_vec=[text11,text12,text13]

In [10]:
doc_cv_vec = txt_vec.transform(document_vec)
lda_test = lda.transform(doc_cv_vec)

In [11]:
for i,lda in enumerate(lda_test):
    print("### ",i)
    topicid=[i for i, x in enumerate(lda) if x == max(lda)]
    print(document_vec[i])
    print(lda," >>> topic",topicid)
    print("")

###  0
an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics,computer software, and online services.
[0.02807884 0.94457812 0.02734304]  >>> topic [1]

###  1
The company's hardware products include the iPhone smartphone,the iPad tablet computer, the Mac personal computer,the iPod portable media player, the Apple Watch smartwatch,the Apple TV digital media player, and the HomePod smart speaker.
[0.02171349 0.73564986 0.24263665]  >>> topic [1]

###  2
there are nany baseball teams in the world,and a lot of team has students many student and pro sports player is playing by same rulebecouse many people can playing baseball,and baseball is enjoyed by many people.
[0.0200292  0.18447222 0.79549858]  >>> topic [2]

