In [ ]:
print("python waked up")

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
zeros_plus = np.zeros((2,3)) + 5
print(zeros_plus)

[[5. 5. 5.]
 [5. 5. 5.]]


In [16]:
aaa = []
print(aaa)

[]


In [17]:
M = len(aaa)
M

0

In [19]:
n_z = np.zeros(3) + 3 * 1.2
print(n_z)

[3.6 3.6 3.6]


In [36]:
for m, n in enumerate(aaa):
    self.N += len(m)

In [43]:
arr = np.random.randint(0, 10, 3)
arr

array([8, 9, 9])

In [46]:
zeros[2,2] += 1

IndexError: index 2 is out of bounds for axis 0 with size 2

In [53]:
M=10
K=5
V=3
alpha = 0.5
bete = 0.5

In [ ]:
z_m_n = []
n_m_z = np.zeros((M, K)) + alpha
n_z_t = np.zeros((K, V)) + bete
n_z = np.zeros(K) + V*bete 

n_z

In [70]:
z_n = np.random.randint(0,10,10)
z_m = z_m_n[1]

IndexError: list index out of range

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.datasets import fetch_20newsgroups

In [3]:
###set datasets.
categorise = ['rec.sport.baseball','sci.space','comp.sys.mac.hardware','comp.windows.x']

news20 = fetch_20newsgroups(categories=categorise)
news = news20.data

news

2.2.22.80\n',
 "From: jcav@ellis.uchicago.edu (JohnC)\nSubject: how do you like the Apple Color OneScanner?\nReply-To: jcav@midway.uchicago.edu\nOrganization: The Royal Society for Putting Things on Top of Other Things\nLines: 13\n\nWe're all set to buy one of these for the office, to use for scanning in\ncolor photographs and for optical character recognition.  We've played with\nthe original grayscale OneScanner and were very pleased.  Is the color model\ncomparable in quality?\n\nAlso, what brand of OCR software would you recommend?  We're leaning toward\nCaere OmniPage.  Any better ideas?  Thanks.\n\n-- \nJohn Cavallino                  |  EMail: jcav@midway.uchicago.edu\nUniversity of Chicago Hospitals |         John_Cavallino@uchfm.bsd.uchicago.edu\nOffice of Facilities Management | USMail: 5841 S. Maryland Ave, MC 0953\nB0 f++ w c+ g++ k+ s++ e h- p   |         Chicago, IL  60637\n",
 "Subject: Re: 68LC040 vs. 68RC040 in Centris 650\nFrom: Bruce@hoult.actrix.gen.nz (Bruce Hoult)

In [20]:
txt_vec = CountVectorizer(news)
txt_vec_fit = txt_vec.fit(news)
word = txt_vec.transform(news)

In [21]:
len(txt_vec.get_feature_names())

34301

In [22]:
vector = word.toarray()

for word,count in zip(txt_vec.get_feature_names()[:], vector[0, :]):
    print(word, count)

nna 0
wannabe 0
want 0
wanted 0
wanting 0
wants 0
war 0
war_ 0
ward 0
wardsgi 0
ware 0
warentee 0
wares 0
warfare 0
wargs 0
warhead 0
warheads 0
warkentin 0
warkentine 0
warm 0
warmed 0
warming 0
warmly 0
warmup 0
warn 0
warned 0
warner 0
warning 0
warnings 0
warp 0
warped 0
warper 0
warranted 0
warranties 0
warranty 0
warren 0
warren1c 0
warrent 0
warrenty 0
warrior 0
wars 0
warwick 0
wary 0
was 1
wash 0
washed 0
washer 0
washers 0
washing 0
washington 0
wasn 0
wason 0
wasp 0
wasps 0
waste 0
wasted 0
wasteful 0
wasteland 0
wastes 0
wasting 0
watarts 0
watcgl 0
watch 0
watched 0
watches 0
watching 0
watcom 0
water 0
waterloo 0
watertown 0
waterwood 0
watkins 0
wats 0
watserv1 0
watsol 0
watson 0
watt 0
wattage 0
watts 0
wau 0
waugaman 0
wave 0
waveforms 0
wavefront 0
waveland 0
wavelength 0
wavelengths 0
waves 0
waving 0
wawers 0
wax 0
way 0
wayne 0
ways 0
wc 0
wc_c 0
wc_len 0
wc_str 0
wcau 0
wcaw 0
wcfields 0
wchar 0
wchar_t 0
wchartoxmstring 0
wcl 0
wd 0
wd90c00 0
wd90c10 0
wd90c11 0