In [1]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer as CV
import numpy
from sklearn.decomposition import LatentDirichletAllocation as LDA

In [2]:
categories = ['rec.sport.baseball', 'sci.space', 'comp.sys.mac.hardware', 'comp.windows.x','talk.politics.guns']

news20 = fetch_20newsgroups(categories=categories)
news = news20.data

In [3]:
cv = CV(max_df=0.5, min_df=5,stop_words='english')
#cv_fit = cv.fit(news)
cv_fit_transform = cv.fit_transform(news)
len(cv.get_feature_names())

9766

In [4]:
lda = LDA(n_components=5,learning_method='online', max_iter=20)

lda_fit = lda.fit(cv_fit_transform)



In [5]:
features = cv.get_feature_names()


for topic in range(5):
    print("topic", topic)
    number_of_topic = lda.components_[topic] 
    word = ','.join(features[i] for i in number_of_topic.argsort()[:-20:-1])
    print(word, "\n")

topic 0
gun,com,people,don,guns,like,writes,article,think,right,control,weapons,firearms,government,law,just,state,know,time 

topic 1
writes,article,com,year,think,university,just,don,nntp,host,good,like,game,baseball,team,time,know,games,day 

topic 2
space,nasa,com,article,writes,mac,gov,nntp,host,apple,university,like,just,know,new,does,data,access,ca 

topic 3
file,com,window,use,mit,program,server,motif,entry,output,available,widget,information,using,set,code,application,version,windows 

topic 4
cs,com,hp,host,writes,university,nntp,article,duke,alomar,ca,thanks,10,12,distribution,800,13,netcom,nl 



In [9]:
text11="an American multinational technology company headquartered in Cupertino, "+ \
        "California, that designs, develops, and sells consumer electronics,"+ \
        "computer software, and online services."

text12="The company's hardware products include the iPhone smartphone,"+ \
        "the iPad tablet computer, the Mac personal computer,"+ \
        "the iPod portable media player, the Apple Watch smartwatch,"+ \
        "the Apple TV digital media player, and the HomePod smart speaker."

text13="there are nany baseball teams in the world,and a lot of team has students "+ \
        "many student and pro sports player is playing by same rule"+ \
        "becouse many people can playing baseball,and baseball is enjoyed by many people."

test1=[text11, text12, text13]

In [10]:
X_test1 = cv.transform(test1)
lda_test1 = lda.transform(X_test1)

AttributeError: 'numpy.ndarray' object has no attribute 'transform'

In [11]:
for i,lda in enumerate(lda_test1):
    print("### ",i)
    topicid=[i for i, x in enumerate(lda) if x == max(lda)]
    print(test1[i])
    print("Score\n", lda)
    print(" >>> topic",topicid)
    print("")

###  0
an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics,computer software, and online services.
Score
 [0.00969892 0.34563551 0.62517205 0.00981236 0.00968116]
 >>> topic [2]

###  1
The company's hardware products include the iPhone smartphone,the iPad tablet computer, the Mac personal computer,the iPod portable media player, the Apple Watch smartwatch,the Apple TV digital media player, and the HomePod smart speaker.
Score
 [0.11759174 0.84680241 0.01197739 0.01179039 0.01183807]
 >>> topic [1]



In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer as TF

In [12]:
cv = TF(max_df=0.5, min_df=5,stop_words='english')
#cv_fit = cv.fit(news)
cv_fit_transform = cv.fit_transform(news)
len(cv.get_feature_names())

9766

In [13]:
lda = LDA(n_components=5,learning_method='online', max_iter=20)

lda_fit = lda.fit(cv_fit_transform)



In [14]:
features = cv.get_feature_names()


for topic in range(5):
    print("topic", topic)
    number_of_topic = lda.components_[topic] 
    word = ','.join(features[i] for i in number_of_topic.argsort()[:-20:-1])
    print(word, "\n")

topic 0
bmug,pyron,skndiv,214,492,4656,padi,lewisville,3556,54909,462,dm,hood,robin,gestures,pr,contribution,sits,suggesting 

topic 1
com,window,university,host,nntp,article,mac,thanks,writes,know,mit,like,cs,apple,does,problem,ca,just,use 

topic 2
gene,mahan,raider,tgv,theporch,lazarus,wright,nashville,macinteresteds,washer,notebooks,unnecessarily,waking,615,crime,7951,297,continuin,capitalist 

topic 3
feustel,dresden,inf,georgia,topaz,steinly,prism,tu,beck,andre,gt0523e,mule,andre_beck,irs,irzr17,elin,gatech,scicom,alphacdc 

topic 4
space,com,gun,nasa,people,writes,article,don,like,gov,guns,henry,just,access,think,government,alaska,moon,digex 



In [22]:
text11="an American multinational technology company headquartered in Cupertino, "+ \
        "California, that designs, develops, and sells consumer electronics,"+ \
        "computer software, and online services."

text12="The company's hardware products include the iPhone smartphone,"+ \
        "the iPad tablet computer, the Mac personal computer,"+ \
        "the iPod portable media player, the Apple Watch smartwatch,"+ \
        "the Apple TV digital media player, and the HomePod smart speaker."

text13="there are nany baseball teams in the world,and a lot of team has students "+ \
        "many student and pro sports player is playing by same rule"+ \
        "becouse many people can playing baseball,and baseball is enjoyed by many people."

test1=[text11, text12, text13]

In [23]:
X_test1 = cv.transform(test1)
lda_test1 = lda.transform(X_test1)

AttributeError: 'numpy.ndarray' object has no attribute 'transform'

In [21]:
for i,lda in enumerate(lda_test1):
    print("### ",i)
    topicid=[i for i, x in enumerate(lda) if x == max(lda)]
    print(test1[i])
    print("\nScore\n", lda)
    print(" >>> topic",topicid)
    print("")

###  0
The company's hardware products include the iPhone smartphone,the iPad tablet computer, the Mac personal computer,the iPod portable media player, the Apple Watch smartwatch,the Apple TV digital media player, and the HomePod smart speaker.

Score
 [0.04130307 0.83354172 0.04130304 0.04130237 0.0425498 ]
 >>> topic [1]

###  1
there are nany baseball teams in the world,and a lot of team has students many student and pro sports player is playing by same rulebecouse many people can playing baseball,and baseball is enjoyed by many people.

Score
 [0.04764177 0.80815146 0.04764164 0.04764104 0.04892409]
 >>> topic [1]

